runs: 1
max_time_steps: 10_000_000

hyperparameters:
  # Example hyperparameters for TD3
  td3:
    batch_size: 128
    network_width: 256
    num_layers: 3
    learning_rate: 0.001
    tau: 0.01
    train_freq: 32
    action_noise_std: 0.4
    gamma: 0.95
    hge_rate_at_start: 0.5 # Use 0.0 for no Heuristic guided exploration
